---
- name: release the public IP address for the instance {{ gcp_name_tag }}
  gcp_compute_address:
    name: "{{ gcp_name_tag }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
