---
- name: Destroy the compute instance with the name {{ gcp_name_tag }}
  gcp_compute_instance:
    name: "{{ gcp_name_tag }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
