---
- name: Get Network details
  gcp_compute_network_facts:
    filters:
    - name = "{{ gcp_name_tag }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: network

- name: Remove firewall rule from Network 
  gcp_compute_firewall:
    name: ssh
    network: "{{ network }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: Remove firewall rule from Network 
  gcp_compute_firewall:
    name: winrm
    network: "{{ network }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: destroy the network for the new compute instance
  gcp_compute_network:
    name: "{{ gcp_name_tag }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
