---
# tasks file for azure-create-virtualnetwork
- name: Create virtual network {{ azure_virtualnetwork_name }} in resource group {{ azure_resourcegroup_name }}
  azure_rm_virtualnetwork:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ azure_virtualnetwork_name }}"
    address_prefixes: "{{ azure_virtualnetwork_address_prefixes }}"