---
- name: create the new compute instance with the name {{ gcp_name_tag }}
  gcp_compute_instance:
    name: "{{ gcp_name_tag }}"
    machine_type: "{{ gcp_machine_type }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk }}"
    metadata:
      startup-script: "{{ lookup('template', gcp_startup_script) }}"
      windows-startup-script-ps1: "{{ lookup('template', gcp_startup_script) }}"
      provisioner: "{{ gcp_provisioner_tag }}"
    network_interfaces:
    - network: "{{ network }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address }}"
        type: ONE_TO_ONE_NAT
    zone: "{{ gcp_zone }}"
    state: present

- name: Wait for ssh to come up
  wait_for: 
    host: "{{ address.address }}" 
    port: "{{ ssh_port }}" 
    state: started
  when:  "{{ 'win' not in instance_os }}"

- name: Wait for winrm to come up
  wait_for: 
    host: "{{ address.address }}" 
    port: "{{ winrm_port }}"  
    state: started
  when:  "{{ 'win' in instance_os }}"

- name: Add host to groupname for the in memory inventory
  add_host: 
    hostname: "{{ address.address }}"
    groupname: gcp_instances